control_dt: 0.02

msg_type: "go"     # "hg" or "go"
imu_type: "torso"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/go2/go2_moe_cts_137000_0.6365.pt"

joint2motor_idx: [3,4,5,0,1,2,9,10,11,6,7,8]

kps: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
default_angles: [  0.1, 0.8, -1.5,
                  -0.1, 0.8, -1.5,
                   0.1, 1.0, -1.5,
                  -0.1, 1.0, -1.5]
obs_scales_ang_vel: 0.25
obs_scales_dof_pos: 1.0
obs_scales_dof_vel: 0.05
command_scale: [3.0, 2.0, 0.5]

action_scale: 0.25
num_actions: 12
num_obs: 45

